#saleor API git 
version: "3.4"

services:
  saleor:
    image: saleor
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    env_file:
      - common.env
      - backend.env
    depends_on:
      - db
      - redis
    volumes:
      - ..:/app

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.20.5
    restart: always
    ports:
      - "9002:80"

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: redis:7.0-alpine
    restart: always
    volumes:
      - saleor-redis:/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # Mailpit UI
    restart: always

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local

